### ISSUE TITLE
Option to overwrite source files (instead of creating new .min files) when not committing back to repo

### ISSUE THREAD

**Issue by ronan-smith** [nizarmah/auto-minify#15]
I'd really like to use this action as part of my simple deployment workflow for deploying a static hand-coded website; currently the workflow just checks out the source code, connects to the server via SFTP, and then transfers across any files that have changed - **no files are written back to the repository.**

The problem is all references in the project point to source files without the `.min` extension so when this action creates new files with the `.min` extension, the minified files aren't loaded by the page so the minification is pointless - I'm not using any other preprocessors so I can't dynamically change the reference in the HTML file.

Would it be possible to add an option to **overwrite the existing source files with the minified versions** instead of creating new copies with the `.min` extension, providing that the option to auto-commit back to the repo is not used?

**Comment by dbjpanda** [comment]
+1

**Comment by dbjpanda** [comment]
+1 for this option.
 
Currently I am using a custom script. Maybe helpful for someone.
```yaml
- name: Minify all CSS & JS inside assets
   uses: nizarmah/auto-minify@master
    with:
       directory: 'assets'
 - name: Remove .min suffix from minified files
    run: find ./assets -depth -name "*.min.*" -exec sh -c 'mv "$1" "${1%.*.*}.${1##*.}"' _ {} \;

```
