### ISSUE TITLE
CSS minification in :not()

### ISSUE THREAD

**Issue by ShockedPlot7560** [nizarmah/auto-minify#27]
Currently, all spaces in the :not() function are removed, breaking most conditions. Example: 
```css
ul > li:not(.class ul > li, .another-class ul > li) {
        display: none;
}
```
 will become : 
```css
ul>li:not(.classul>li,.another-classsul>li){display:none;}
```
