### ISSUE TITLE
Help with an error

### ISSUE THREAD

**Issue by its-pablo** [nizarmah/auto-minify#28]
I keep receiving this error halfway through the build:
![image](https://user-images.githubusercontent.com/78528552/154777728-2b2c0951-7693-4e7d-baa7-63a82cfbcc1c.png)

Here's my yml setup:
```yml
name: Auto Minifier CSS

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          overwrite: false
          directory: .
          maxdepth: 20
      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
```

Could somebody diagnose?
