### ISSUE TITLE
Expected format {org}/{repo}[/path]@ref. Actual 'nizarmah/auto-minify'

### ISSUE THREAD

**Issue by ardacebi** [nizarmah/auto-minify#7]
Hi,

I'm trying to use the simplest form on my project. Even though I'm doing everything right (at least for me), I'm getting this error:

`Expected format {org}/{repo}[/path]@ref. Actual 'nizarmah/auto-minify'`

My file:

```
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
       - uses: actions/checkout@v2

       - name: Auto Minify
         uses: nizarmah/auto-minify

       # Auto commits minified files to the repository
       # Ignore it if you don't want to commit the files to the repository 
       - name: Auto committing minified files
         uses: stefanzweifel/git-auto-commit-action@v3.0.0
         with:
           commit_message: "Automated: Minified CSS files"
           branch: ${{ github.ref }}

```

Thanks!
